### PR TITLE
Fix moving class between projects

### LINKED ISSUE #60: False positive when moving a class from one package to dependent package
## What happened?

If you move class `Foo` from project `core` to project `dependency`, where `core` depends on `dependency` as `api`, then revapi will create a spurious error saying it's a breaking change, even though the class is still on the classpath when using `core`.

## What did you want to happen?

Revapi should not create an error in this case.

### PR DESCRIPTION
**Pull request by CRogers**
Fixes #60.

## Before this PR
If you move a public java class between one project and `api` project dependency, revapi will tell you the class has been removed. This is incorrect, assuming you are using a dependency resolver, as you will pull in the other jar and have access to it's types.

## After this PR
==COMMIT_MSG==
Moving a java class from a project to a dependency of that project is allowed, so long as the dependent project is at the `api` level.
==COMMIT_MSG==

We essentially include project dependency jars at `api` level in our revapi analysis.

## Possible downsides?
Since we are inspecting a larger API surface (before: just your project's jar, after: your project's jar and all jars depended on by your project in the repo), there's a higher risk of OOMing.

### CODE REVIEW

File: src/main/java/com/palantir/gradle/revapi/RevapiPlugin.java [hunk 1]
```diff
@@ -60,14 +61,40 @@ public void apply(Project project) {
...
+                        conf.setCanBeConsumed(false);
                     });
 
-                    task.dependsOn(allJarTasksIncludingDependencies(project, revapiNewApi));
+                    Configuration revapiNewApiElements = project.getConfigurations()
+                            .create("revapiNewApiElements", conf -> {
+                                conf.extendsFrom(project.getConfigurations()
+                                        .getByName(JavaPlugin.API_ELEMENTS_CONFIGURATION_NAME));
+                                conf.setCanBeConsumed(false);
+                            });
```
Comment (dansanduleac) [inline src/main/java/com/palantir/gradle/revapi/RevapiPlugin.java:79]: this will resolve the runtime variant of transitives, so you probably want to set a usage attribute on here, essentially copying what attributes compileClasspath sets:
https://github.com/gradle/gradle/blob/193008197a7b450fd57970f8598ca3f1ffc810b7/subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/JvmPluginsHelper.java#L224-L230

some of these were not always public / change with the gradle version though, so I'd almost recommend just stealing the attributes from compileClasspath and setting them one by one

Comment (dansanduleac) [reply src/main/java/com/palantir/gradle/revapi/RevapiPlugin.java:79]: and do the same for `revapiNewApi`

File: src/main/java/com/palantir/gradle/revapi/RevapiPlugin.java [hunk 2]
```diff
@@ -60,14 +61,40 @@ public void apply(Project project) {
...
+                                .flatMap(jar -> jar.getOutputs().getFiles().getFiles().stream())
+                                .collect(Collectors.toSet());
+
+                        return Sets.union(
+                                Collections.singleton(thisJarFile),
+                                Sets.intersection(revapiNewApiElements.resolve(), allJarFiles));
+                    }));
+                    task.getNewApiDependencyJars()
+                            .set(project.provider(() -> Sets.difference(
+                                    revapiNewApi.resolve(), task.getNewApiJars().get())));
```
Comment (dansanduleac) [inline src/main/java/com/palantir/gradle/revapi/RevapiPlugin.java]: I wonder if it's nicer to just work with `FileCollection` apis as they also support plus and minus, and is lazy by default so you don't need providers

Comment (dansanduleac) [reply src/main/java/com/palantir/gradle/revapi/RevapiPlugin.java]: they are also `Buildable`, so the jar's `getOutputs().getFiles()` will remember what task builds it, and that will propagate to the property if you do `Property.set(that FileCollection)`

Comment (dansanduleac) [reply src/main/java/com/palantir/gradle/revapi/RevapiPlugin.java]: in any case, I'd also make sure that anything you call resolve on is either added directly via `task.getInputs().files(...)`, or set on `@CompileClasspath` properties that the task exposes

File: src/main/java/com/palantir/gradle/revapi/RevapiPlugin.java [hunk 3]
```diff
@@ -60,14 +61,40 @@ public void apply(Project project) {
...
+                                .getFiles()
+                                .getSingleFile();
+
+                        Set<File> allJarFiles = allJarTasks.get().stream()
+                                .flatMap(jar -> jar.getOutputs().getFiles().getFiles().stream())
+                                .collect(Collectors.toSet());
+
+                        return Sets.union(
+                                Collections.singleton(thisJarFile),
+                                Sets.intersection(revapiNewApiElements.resolve(), allJarFiles));
```
Comment (dansanduleac) [inline src/main/java/com/palantir/gradle/revapi/RevapiPlugin.java]: here you essentially want "internal dependencies", so excluding external deps.
You can do that much nicer directly from the configuration like so, and it gives you a lazy `FileCollection` too:

```java
conf.getIncoming()
        .artifactView(vc -> vc.componentFilter(ci -> ci instanceof ProjectComponentIdentifier))
        .getFiles()
```

Then you don't need the intersection, that is the only thing FileCollections don't support

File: src/main/java/com/palantir/gradle/revapi/RevapiPlugin.java [hunk 4]
```diff
@@ -60,14 +61,40 @@ public void apply(Project project) {
                     Configuration revapiNewApi = project.getConfigurations().create("revapiNewApi", conf -> {
                         conf.extendsFrom(
                                 project.getConfigurations().getByName(JavaPlugin.COMPILE_CLASSPATH_CONFIGURATION_NAME));
+                        conf.setCanBeConsumed(false);
```
Comment (dansanduleac) [inline src/main/java/com/palantir/gradle/revapi/RevapiPlugin.java:68]: actually why do we craete a new configuration here, rather than just use `compileClasspath`?

Comment (CRogers) [reply src/main/java/com/palantir/gradle/revapi/RevapiPlugin.java:68]: I think it's because we originally resolved runtime elements until a few weeks ago - probably don't need to at all now :)

**Comment by dansanduleac** [comment]
👍

**Comment by CRogers** [comment]
:+1:
