### PR TITLE
If no versions of library have been published, skip analysis

### LINKED ISSUE #110: No documented way of creating new sub-project
## What happened?

When creating a new subproject in an existing project with revapi enabled, revapi errors out with no apparent way of marking the break through the config interface (it always fails with a "Failed to resolve old API"-type error).

The errors in the template take the pattern of:

```
  We tried version $latest but it failed with errors:
  Could not find $project:$pkg:$latest.
  Searched in the following locations:
    - ...
    - ...

...
```

## What did you want to happen?

Either a command to tell revapi that a project was just added, or a way to get the `revapiAcceptAllBreaks` command to work in those circumstances. If there already exists a way to handle this, we should document it in the readme.

### PR DESCRIPTION
**Pull request by CRogers**
Fixes #110.

## Before this PR
If you create a new project, and apply `gradle-revapi` to it, it will fail because there are no published artifacts to test against.

## After this PR
==COMMIT_MSG==
If there are no published versions of the library to check against, the analysis tasks will be skipped. This allows you to apply the revapi plugin to new Gradle projects.
==COMMIT_MSG==

## Possible downsides?
None I can think of.

### CODE REVIEW

File: src/test/groovy/com/palantir/gradle/revapi/RevapiSpec.groovy [hunk 1]
```diff
@@ -311,6 +311,29 @@ class RevapiSpec extends IntegrationSpec {
...
+            apply plugin: 'java-library'
+            
+            repositories {
+                mavenCentral()
+            }
+            
+            revapi {
+                oldGroup = 'does.not'
+                oldName = 'exist'
+                oldVersion = '1.0.0'
```
Comment (dansanduleac) [inline src/test/groovy/com/palantir/gradle/revapi/RevapiSpec.groovy:327]: how does this get set normally, if you don't have a version?
would it be set to something or empty? if empty, we should test that code path

Comment (CRogers) [reply src/test/groovy/com/palantir/gradle/revapi/RevapiSpec.groovy:327]: Normally it gets set to the last 3 git tags (it's a list underneath). The "no git tags" case is tested by [this test](https://github.com/palantir/gradle-revapi/blob/bbe721711ddfc44b92896c0232e792760a1d9ae5/src/test/groovy/com/palantir/gradle/revapi/RevapiSpec.groovy#L234) ([PR for that change](https://github.com/palantir/gradle-revapi/pull/120)).

Comment (dansanduleac) [reply src/test/groovy/com/palantir/gradle/revapi/RevapiSpec.groovy:327]: ah ok then

**Review by dansanduleac — APPROVED** [review]
